---
virtualenv:
    name: "shoutoutsvenv"

requirements:
    file: "requirements/dev.txt"

collectstatic: true

npm: true

bower: true

gulp: true

apache_config:
    server_path: "shoutouts"

arbitrary_command:
    - "python"
    - "--version"

another_command:
    - "ls"
    - "/vagrant"
